export default {
  'AL - Alabama': 'AL',
  'AK - Alaska': 'AK',
  'AZ - Arizona': 'AZ',
  'AR - Arkansas': 'AR',
  'CA - California': 'CA',
  'CO - Colorado': 'CO',
  'CT - Connecticut': 'CT',
  'DE - Delaware': 'DE',
  'DC - District of Columbia': 'DC',
  'FL - Florida': 'FL',
  'GA - Georgia': 'GA',
  'HI - Hawaii': 'HI',
  'ID - Idaho': 'ID',
  'IL - Illinois': 'IL',
  'IN - Indiana': 'IN',
  'IA - Iowa': 'IA',
  'KS - Kansas': 'KS',
  'KY - Kentucky': 'KY',
  'LA - Louisiana': 'LA',
  'ME - Maine': 'ME',
  'MD - Maryland': 'MD',
  'MA - Massachusetts': 'MA',
  'MI - Michigan': 'MI',
  'MN - Minnesota': 'MN',
  'MS - Mississippi': 'MS',
  'MO - Missouri': 'MO',
  'MT - Montana': 'MT',
  'NE - Nebraska': 'NE',
  'NV - Nevada': 'NV',
  'NH - New Hampshire': 'NH',
  'NJ - New Jersey': 'NJ',
  'NM - New Mexico': 'NM',
  'NY - New York': 'NY',
  'NC - North Carolina': 'NC',
  'ND - North Dakota': 'ND',
  'OH - Ohio': 'OH',
  'OK - Oklahoma': 'OK',
  'OR - Oregon': 'OR',
  'PA - Pennsylvania': 'PA',
  'RI - Rhode Island': 'RI',
  'SC - South Carolina': 'SC',
  'SD - South Dakota': 'SD',
  'TN - Tennessee': 'TN',
  'TX - Texas': 'TX',
  'UT - Utah': 'UT',
  'VT - Vermont': 'VT',
  'VA - Virginia': 'VA',
  'WA - Washington': 'WA',
  'WV - West Virginia': 'WV',
  'WI - Wisconsin': 'WI',
  'WY - Wyoming': 'WY',
  'AS - American Samoa': 'AS',
  'GU - Guam': 'GU',
  'MP - Northern Mariana Islands': 'MP',
  'PR - Puerto Rico': 'PR',
  'VI - Virgin Islands': 'VI',
  'FM - Federated States of Micronesia': 'FM',
  'MH - Marshall Islands': 'MH',
  'PW - Palau': 'PW',
  'AA - U.S. Armed Forces – Americas[4]': 'AA',
  'AE - U.S. Armed Forces – Europe[5]': 'AE',
  'AP - U.S. Armed Forces – Pacific[6]': 'AP',
  'CM - Northern Mariana Islands': 'CM',
  'CZ - Panama Canal Zone': 'CZ',
  'NB - Nebraska': 'NB',
  'PI - Philippine Islands': 'PI',
  'TT - Trust Territory of the Pacific Islands': 'TT',
}
